GET http://localhost:5000/profilPekerja

###
GET http://localhost:5000/profilPekerja/1

###
POST http://localhost:5000/profilPekerja
Content-Type: application/json

{
    "nama_depan": "Fery21321",
    "nama_belakang": "Nugraha",
    "email": "nug321nug@gmail.com",
    "profesi": "Fullstack Developer",
    "panggilan": "testing",
    "tempat_lahir": "Semarang",
    "tanggal_lahir": "1995-08-20",
    "jns_kel": "L",
    "nomor_hp": "123456789",
    "domisili": "Semarang",
    "detail_tentang_saya": "ini isi panjang tentang saya, bla bla bla",
    "password": "`12sdfg&*90"
}

###
PUT http://localhost:5000/profilPekerja/1
Content-Type: application/json

{
    "nama_depan": "POST Depan",
    "nama_belakang": "Nama Belakang",
    "email": "depanbelakang@gmail.com",
    "profesi": "Programmer",
    "panggilan": "Depan Belakang",
    "tempat_lahir": "Bandung",
    "tanggal_lahir": "2023-11-06",
    "jns_kel": "P",
    "nomor_hp": "0812399999",
    "domisili": "Jawa Barat",
    "detail_tentang_saya": "ini merupakan detail tentang saya",
    "id_pekerja_edit": "1"
}

###
DELETE http://localhost:5000/profilPekerja/1

###
PUT http://localhost:5000/deleteChangesProfilPekerja/3
Content-Type: application/json

{
    "id_pekerja_delete": 3
}

###
GET http://localhost:5000/verifiedPassword?password=123456789&hasPassword=$2b$10$pHsx8GlVxTqt.z6WkmtMSuf1uy7xP6yIDXIcAEdTHdVJB315pF0v2