GET http://localhost:5000/profilPekerja

###
POST http://localhost:5000/profilPekerja
Content-Type: application/json

{
    "nama_depan": "Rizky",
    "nama_belakang": "Ananto",
    "email": "testing@gmail.com",
    "profesi": "Fullstack Developer",
    "panggilan": "Rizky",
    "tempat_lahir": "Jakarta",
    "tanggal_lahir": "1995-08-20",
    "jns_kel": "L",
    "nomor_hp": "081219058757",
    "domisili": "Jakarta",
    "detail_tentang_saya": "ini isi panjang tentang saya, bla bla bla",
    "password": "123456789"
}

###
GET http://localhost:5000/verifiedPassword?password=123456789&hasPassword=$2b$10$pHsx8GlVxTqt.z6WkmtMSuf1uy7xP6yIDXIcAEdTHdVJB315pF0v2